database:
  image: mariadb:latest
  environment:
    MARIADB_ROOT_PASSWORD: "redhat"
    DB_NAME: "studentapp"
  ports:
    - "3306:3306"


backend:
  build: ./backend
  ports:
    - "8080:8080"
  environment:
    DB_NAME: "studentapp"
    DB_USER: "root"
    DB_PASSWORD: "redhat"
    DB_HOST: "database"

frontend:
  build: ./frontend
  ports:
    - "80:80"
  environment:
    PUBLIC_IP: "13.212.151.46"

